# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4

    - name: Copy committed build to /var/www/html
      run: |
        sudo cp -r build/* /var/www/html
      working-directory: ${{github.workspace}}

